### PR TITLE
Fixing ParsePath on Windows

### PR DESCRIPTION
**Pull request by gamelaster**

### CODE REVIEW

**Comment by jmjuanes** [comment]
Adding `path = path.substr(1);` now works on Windows?

**Comment by gamelaster** [comment]
Yes, the p.pathname returns:
"/C:/something..." so first / is unasked

**Comment by jmjuanes** [comment]
Ok, thanks!

**Comment by jmjuanes** [comment]
captura de pantalla 2016-05-16 a las 18 25 48

I think that is not necessary to remove the first `/` from `/C:/something...`....

In fact, if you use `mainWindow.loadUrl('file://' + __dirname + '/index.ejs');`, you don't need to remove the `/` from the path...

**Comment by gamelaster** [comment]
Hmm, interesting, I don't know, but without this fix its just don't work, it's say file not found.

**Pull request merged**
