### PR TITLE
Adding error handling

### PR DESCRIPTION
**Pull request by gamelaster**

### CODE REVIEW

**Comment by gamelaster** [comment]
Wait! The non-ejs "non-utf8" files don't work! Im working on it!

**Comment by gamelaster** [comment]
Now it's ready!

**Comment by jmjuanes** [comment]
Perfect! Thanks a lot!!  :)

**Comment by jmjuanes** [comment]
Hi @GAMELASTER 

I am trying this new version, but with non-ejs files doesn't work... It says: 

```
Failed to load resource: net::ERR_NOT_IMPLEMENTED
file:///*********/public/js/renders.js 
```

**Comment by jmjuanes** [comment]
Fixed. Replaced 

``` javascript
return callback({ data: content, mimeType: mimet });
```

 with 

``` javascript
return callback({ data: new Buffer(content), mimeType: mimet });
```

**Comment by gamelaster** [comment]
@jmjuanes 
Well, for me non-ejs files worked good. Interesting...
image
(On newest master)
PNG dont work, where style.css is working good.
https://github.com/jmjuanes/electron-ejs/blob/master/index.js#L34
If you look here, you setting the output will be the UTF8, but later in
https://github.com/jmjuanes/electron-ejs/blob/master/index.js#L46
is content again converted to utf8. The converting to UTF8 is needed only when rendering the .ejs, because ejs.render function not handling buffers, but UTF8 strings.

My idea is:
First check the extension, if its ejs, render EJS via ejs.renderFile (we dont need to use fs.readFile), otherwise its make a buffer from fs.readFile and return it, so in this situation we dont must solve a encoding and other things

**Comment by jmjuanes** [comment]
Oops, this is true, PNG files doesn't work...

My first idea was using only `content.toString('utf8')` when the extension is `.ejs`, but I think that your idea is better, and it will resolve the encoding problems in all cases.

**Comment by gamelaster** [comment]
@jmjuanes 
You will do it or I can do it?
btw, its needed to implement handling the EJS template errors (write somewhere)

**Comment by jmjuanes** [comment]
@GAMELASTER You can do it :)

I have added you to the repo as a collaborator. But please, don't publish directly to the `master` branch, create a new branch and do the changes here. Then we will merge the two branches :)

**Pull request merged**
